### ISSUE TITLE
Attempting to create a second center results in an unknown state [video attached]

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/ForgetmeNot3#1]
[This video](https://www.dropbox.com/s/k7b1tquf5pwp1ap/Forget-me-not-center-bug.MOV?dl=0) shows the bug better than I will describe it.

**Comment by bigjosh** [comment]
Ah, good one! I tried to cheat and combine the `RESET` and `BLOOM` states (using a semistate called `BLOOM_0`), and of course it bit me.

Now there is a proper `RESET` state and `BLOOM` is just bloom. It also made possible a better UI whereby now the reset transition has a visible phenotype and we stay in reset until the button is lifted, which I think feels better. 

Good?
